from flask import Flask, request, jsonify
from ultralytics import YOLO
from PIL import Image
import io
import base64
from flask_cors import CORS
import os
import google.generativeai as genai
from dotenv import load_dotenv
import json

# --- 1. CONFIGURATION ---
load_dotenv()
app = Flask(__name__)
CORS(app)

print("⏳ Starting Agri-Sentry (Gemini 2.5 Edition)...")

# --- 2. SETUP GEMINI ---
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    print("⚠️ CRITICAL: GEMINI_API_KEY missing in .env file!")
else:
    genai.configure(api_key=GEMINI_API_KEY)

# --- 3. ROBUST GENERATION FUNCTION ---
def generate_with_fallback(image, prompt):
    """
    Uses the models CONFIRMED to exist in your system check.
    """
    models_to_try = [
        'gemini-2.5-pro',       # Priority 1: Best Intelligence (Confirmed available)
        'gemini-2.5-flash',     # Priority 2: Best Speed (Confirmed available)
        'gemini-2.0-flash',     # Priority 3: Previous Stable
        'gemini-pro-vision'     # Priority 4: Legacy Fallback
    ]

    for model_name in models_to_try:
        try:
            print(f"🔄 Connecting to: {model_name}...")
            model = genai.GenerativeModel(model_name)
            response = model.generate_content([prompt, image])
            print(f"✅ Success! Analysis generated by {model_name}")
            return response
        except Exception as e:
            print(f"⚠️ {model_name} failed. Trying next...")
            continue 
    
    raise Exception("All AI models failed. Check Internet/Quota.")

# --- 4. LOAD YOLO MODELS ---
try:
    print("... Loading Disease Model")
    disease_model = YOLO('best_disease.pt')
except:
    disease_model = None

try:
    print("... Loading Pest Model")
    pest_model = YOLO('best_pest.pt')
except:
    pest_model = None

# --- 5. HELPER FUNCTIONS ---
def process_base64(base64_string):
    if "base64," in base64_string:
        base64_string = base64_string.split("base64,")[1]
    return Image.open(io.BytesIO(base64.b64decode(base64_string)))

def get_yolo_prediction(model, image):
    if not model: return "Model Inactive"
    results = model(image)
    detections = []
    for result in results:
        for box in result.boxes:
            if float(box.conf[0]) > 0.3:
                detections.append(f"{model.names[int(box.cls[0])]}")
    return ", ".join(detections) if detections else "Uncertain"

# --- 6. ROUTE: DIAGNOSIS ---
@app.route('/api/scans/diagnose', methods=['POST'])
def diagnose_specific_language():
    try:
        data = request.json
        image = process_base64(data['image'])
        target_lang = data.get('language', 'en') 
        
        yolo_result = get_yolo_prediction(disease_model, image)
        print(f"🌿 YOLO Scan: {yolo_result}")

        lang_map = {'en': "English", 'hi': "Hindi", 'or': "Odia"}
        selected_language_name = lang_map.get(target_lang, "English")

        prompt = f"""
        You are an Expert Agronomist.
        INPUT: Image + YOLO Scan: "{yolo_result}"
        TASK: Diagnosis report in **{selected_language_name}**.
        JSON STRUCTURE:
        {{
            "diagnosis": {{
                "diseaseName": "Name in {selected_language_name}",
                "pathogen": "Scientific Name",
                "confidence": 0.95,
                "severity": "high",
                "description": "Analysis in {selected_language_name}.",
                "treatments": ["Step 1 ({selected_language_name})", "Step 2", "Step 3"]
            }}
        }}
        """

        response = generate_with_fallback(image, prompt)
        
        text = response.text.strip()
        if text.startswith("```json"): text = text[7:-3]
        elif text.startswith("```"): text = text[3:-3]
        
        return jsonify(json.loads(text))

    except Exception as e:
        print(f"❌ Error: {e}")
        return jsonify({"error": str(e)}), 500

# --- 7. ROUTE: PEST MONITOR (With Strict Validation) ---
@app.route('/api/scans/monitor', methods=['POST'])
def monitor_pests():
    try:
        data = request.json
        image = process_base64(data['image'])
        target_lang = data.get('language', 'en')
        
        # YOLO Scan
        yolo_result = get_yolo_prediction(pest_model, image)
        
        lang_map = {'en': "English", 'hi': "Hindi", 'or': "Odia"}
        lang_name = lang_map.get(target_lang, "English")

        # --- STRICT GATEKEEPER PROMPT ---
        prompt = f"""
        You are a Senior Entomologist.
        INPUT: Image + YOLO Scan: "{yolo_result}"
        
        CRITICAL VALIDATION STEPS (Do this first):
        1. **Is this a real photo of a plant/field?** - If it is a black screen, an icon, a drawing, or a random object -> RETURN "INVALID".
        2. **Are pests visible?**
           - If the plant looks clean and healthy with no bugs/damage -> RETURN "HEALTHY".
        
        TASK:
        - If INVALID: Return pestName="Analysis Failed", severity="invalid".
        - If HEALTHY: Return pestName="Crop is Healthy", severity="healthy".
        - If PESTS FOUND: Identify them and provide specific control strategy in **{lang_name}**.

        OUTPUT JSON STRUCTURE (Strict):
        {{
            "monitoring": {{
                "status": "infested/healthy/invalid", 
                "pestName": "Name or 'Healthy' or 'Invalid'",
                "scientificName": "Scientific Name or 'N/A'",
                "severity": "high/medium/low/healthy/invalid",
                "count": "Estimate count or '0'",
                "description": "Analysis in {lang_name}. If invalid, explain why.",
                "treatments": ["Step 1", "Step 2", "Step 3"]
            }}
        }}
        """

        response = generate_with_fallback(image, prompt)
        
        text = response.text.strip()
        if text.startswith("```json"): text = text[7:-3]
        elif text.startswith("```"): text = text[3:-3]
        
        return jsonify(json.loads(text))

    except Exception as e:
        print(f"❌ Pest Monitor Error: {e}")
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    print("🚀 Agri-Sentry AI Live on Port 5001")
    app.run(host='0.0.0.0', port=5001, debug=True)